clean:
	rm hashtable list

hash: symtablehash.c testsymtab.c
	gcc -ansi -pedantic -Wall -o hashtable symtablehash.c testsymtab.c

list: symtablelist.c testsymtab.c
	gcc -ansi -pedantic -Wall -o list symtablelist.c    testsymtab.c
     	
